# Generated by Django 5.1.6 on 2025-03-21 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelconfig',
            name='encoder',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='modelconfig',
            name='scaler',
            field=models.CharField(max_length=50),
        ),
    ]
