# Generated by Django 5.1.6 on 2025-07-15 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0003_alter_savedmodel_accuracy'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelconfig',
            name='training_time',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
