# Generated by Django 5.1.6 on 2025-07-06 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0003_add_feature_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelconfig',
            name='feature_types',
            field=models.JSONField(default=dict),
        ),
    ]
