# Generated by Django 5.1.6 on 2025-03-23 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0004_rename_user_id_leaderboard_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedmodel',
            name='saved_file_name',
            field=models.CharField(default='Untitled', max_length=255),
        ),
    ]
