# Generated by Django 5.1.6 on 2025-07-24 01:37

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0004_modelconfig_training_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userachievement',
            name='achievement',
        ),
        migrations.RemoveField(
            model_name='userbadge',
            name='badge',
        ),
        migrations.RemoveField(
            model_name='leaderboard',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userachievement',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userbadge',
            name='user',
        ),
        migrations.AlterField(
            model_name='savedmodel',
            name='encoder_file',
            field=models.FileField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to='saved_encoders/'),
        ),
        migrations.AlterField(
            model_name='savedmodel',
            name='model_file',
            field=models.FileField(storage=storages.backends.s3.S3Storage(), upload_to='saved_models/'),
        ),
        migrations.AlterField(
            model_name='savedmodel',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='savedmodel',
            name='scaler_file',
            field=models.FileField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to='saved_scalers/'),
        ),
        migrations.AlterField(
            model_name='savedmodel',
            name='target_encoder',
            field=models.FileField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to='saved_target_encoders/'),
        ),
        migrations.AlterField(
            model_name='uploadeddataset',
            name='dataset',
            field=models.FileField(help_text='Upload CSV, XLS, or XLSX files', storage=storages.backends.s3.S3Storage(), upload_to='uploads/'),
        ),
        migrations.DeleteModel(
            name='Achievements',
        ),
        migrations.DeleteModel(
            name='Badges',
        ),
        migrations.DeleteModel(
            name='LeaderBoard',
        ),
        migrations.DeleteModel(
            name='UserAchievement',
        ),
        migrations.DeleteModel(
            name='UserBadge',
        ),
    ]
