# Generated by Django 5.1.6 on 2025-04-04 04:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0005_savedmodel_saved_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedmodel',
            name='encoder_file',
            field=models.FileField(default=django.utils.timezone.now, upload_to='saved_encoders/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='savedmodel',
            name='scaler_file',
            field=models.FileField(default=django.utils.timezone.now, upload_to='saved_scalers/'),
            preserve_default=False,
        ),
    ]
