# Generated by Django 5.1.6 on 2025-04-04 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0006_savedmodel_encoder_file_savedmodel_scaler_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='savedmodel',
            old_name='config_id',
            new_name='config',
        ),
    ]
