# Generated by Django 5.1.6 on 2025-04-04 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0007_rename_config_id_savedmodel_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedmodel',
            name='config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_app.modelconfig'),
        ),
    ]
