# Generated by Django 5.1.6 on 2025-03-21 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0002_alter_modelconfig_encoder_alter_modelconfig_scaler'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedmodel',
            name='file_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='backend_app.uploadedfile'),
            preserve_default=False,
        ),
    ]
