# Generated by Django 5.1.6 on 2025-03-21 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0003_savedmodel_file_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leaderboard',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='modelconfig',
            old_name='file_id',
            new_name='file',
        ),
        migrations.RenameField(
            model_name='modelconfig',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='savedmodel',
            old_name='file_id',
            new_name='file',
        ),
        migrations.RenameField(
            model_name='savedmodel',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='uploadedfile',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='userachievement',
            old_name='achievement_id',
            new_name='achievement',
        ),
        migrations.RenameField(
            model_name='userachievement',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='userbadge',
            old_name='badge_id',
            new_name='badge',
        ),
        migrations.RenameField(
            model_name='userbadge',
            old_name='user_id',
            new_name='user',
        ),
    ]
